
        // Automatically generated file. Do not edit.
        
        package org.phylowidget;
        
        /**
            The Build class provides information on this build of PhyloWidget.
            This class is automatically generated by the Ant build file.
        */
        public interface Build {
        
            /** The version number of this PulpCore build. */
            public static final String PROJECT = "PhyloWidget";
            
            /** The build date. */
            public static final String BUILD_DATE = "February 13 2009";
        }
        